
dependencies:
- python=3.8
- jupyter

- pip:
  - edward2 == 0.0.2
  - gpflow #== 2.3.0
  - numpy #== 1.19.2
  - tensorflow #== 2.7.0
  - pandas #== 1.1.3
  - matplotlib
  - seaborn #== 0.11.0
  #- logging
  #- typing
  #- os
  #- gc
  #- time
  #- pickle
  #- functools
  #- multiprocessing
  # - shapely
  # - geopandas==0.3.0
  # - pyshp==1.2.10
  # - pandas


 #- conda: 
  #- plotly
  